### ISSUE TITLE
option to specify lz4 for zfs compression instead of gzip

### ISSUE THREAD

**Issue by cactus** [smortex/portshaker#2]
Would it be possible to make the zfs compression algo that portshaker uses configurable?
I would prefer to use lz4 for zfs compression. Right now gzip is used and this is not configurable from what I can see.
It would also be nice to have an option to set compression on the zfs ports tree that portshaker creates too. It doesn't currently compress that zfs fs at all.

**Comment by smortex** [comment]
Hello, and sorry for the late answer,

I have no objection for an optional `${zfs_compression}` variable in the configuration file to make the method changeable when a ZFS filesystem is created for a source ports tree.

When a ZFS snapshot is cloned for building a target ports tree, no compression is set for this new FS, mostly because I consider the target ports tree as a staging FS that will be destroyed on the next `portshaker(8)` and the overhead of compression is likely to have a wrong performance hit. However, I also read that sometimes spending more time on CPU to compress data was faster than storing the uncompressed data on non-SSD hard disks, but I could not measure it, and because of SSDs it might not be true anymore.

Do you have an opinion about this? Would two `$source_zfs_compression` and `$target_zfs_compression` fit your needs ?

**Comment by cactus** [comment]
> Do you have an opinion about this? 

As to your question about compression for the clone, lz4 is pretty fast in comparison to zlib compression, so I would probably end up turning it on even though I run my personal builds on an SSD drive -- simply because I have lots of cpu to spare and the impact of lz4 is not terrible. I can completely understand some people not wanting to use any compression at all though.

> Would two $source_zfs_compression and $target_zfs_compression fit your needs ?

That would fit my needs perfectly.

**Comment by smortex** [comment]
I have just committed 1a5d781.  Can you please test and tell me if further work is required?

**Comment by cactus** [comment]
@smortex so far it seems to be working well (had to hand edit my portshaker.subr with your changes here). Once I zfs destroyed my zfs filesystems (freebsd ports tree and a git repo tree), portshaker recreated them with lz4 as specified in my config.

Thanks!

some output

```
$ sudo portshaker -U -M -v -v
Debug 16:40:38] update 
[Info  16:40:38] Updating 'freebsd' source ports tree with method 'portsnap'.
[Debug 16:40:38] Running 'portsnap  -p /tank/portshaker/freebsd alfred'.
... <elided for brevity> ....
[Debug 16:40:39] Running 'zfs destroy tank/portshaker/freebsd@portshaker-2015-04-06:16:40:16'.
[Debug 16:40:39] Running 'zfs destroy tank/portshaker/freebsd@portshaker-2015-04-06:16:40:37'.
[Debug 16:40:39] Running 'zfs snapshot tank/portshaker/freebsd@portshaker-2015-04-06:16:40:39'.
[Debug 16:40:39] update 
[Info  16:40:39] Updating 'nullage' source ports tree with method 'git'.
[Debug 16:40:39] Running 'git pull'.
... <elided for brevity> ....
[Debug 16:40:39] Running 'zfs destroy tank/portshaker/nullage@portshaker-2015-04-06:16:40:37'.
[Debug 16:40:39] Running 'zfs snapshot tank/portshaker/nullage@portshaker-2015-04-06:16:40:39'.
[Debug 16:40:39] clone_to -z tank/main -t /tank/ports
[Info  16:40:39] Cloning '/tank/portshaker/freebsd' to '/tank/ports'.
[Debug 16:40:39] Running 'zfs destroy -r tank/ports'.
[Debug 16:40:39] Running 'zfs clone tank/portshaker/freebsd@portshaker-2015-04-06:16:40:39 tank/ports'.
[Debug 16:40:39] Running 'zfs set mountpoint=/tank/ports tank/ports'.
[Debug 16:40:39] Running 'zfs set compression=lz4 tank/ports'.
[Debug 16:40:39] merge_to -m freebsd -t /tank/ports
[Info  16:40:39] Merging '/tank/portshaker/nullage' to '/tank/ports'.
[Debug 16:40:39] Processing multimedia/test.
[Debug 16:40:39] multimedia/test is a new port.
[Debug 16:40:39] Copying '/tank/portshaker/nullage/multimedia/test' to '/tank/ports/multimedia/test'.
[Debug 16:40:39] Updating multimedia Makefile.
```

```
$ zfs get -r compression
tank/ports                                              compression  lz4       local
tank/portshaker/freebsd                                 compression  lz4       local
tank/portshaker/freebsd@portshaker-2015-04-06:16:40:37  compression  -         -
tank/portshaker/freebsd@portshaker-2015-04-06:16:40:39  compression  -         -
tank/portshaker/nullage                                 compression  lz4       local
tank/portshaker/nullage@portshaker-2015-04-06:16:40:39  compression  -         -
```

```
$ cat portshaker.conf
use_zfs="YES"
mirror_base_dir="/tank/portshaker"
ports_trees="main"
main_ports_tree="/tank/ports"
main_merge_from="freebsd nullage"
poudriere_ports_mountpoint="/tank/ports"
default_poudriere_tree="default"
source_zfs_compression="lz4"
target_zfs_compression="lz4"

**Comment by smortex** [comment]
Great, this will be part of 2.0.0.  Thanks!
