### ISSUE TITLE
Succinctly patching Makefiles

### ISSUE THREAD

**Issue by steakknife** [smortex/portshaker#6]
Thanks for this utility.

Is there more compact Makefile patching available ([better than this](https://gist.github.com/steakknife/82cb2db21388c2b6b475)) than overlays maintaining full-text Makefiles?

#### Desired behavior

```make
# <some overlay tree>/security/krb5/ldap-sasl-option.mk
OPTIONS_DEFINE+=     LDAP_SASL
LDAP_SASL_DESC=     Prefer OpenLDAP with SASL support
LDAP_SASL_USE=     WANT_OPENLDAP_SASL= yes
```

**Comment by smortex** [comment]
Sorry for late answer
`portshaker(1)` compares whole file hierarchies, so you **must** copy the whole directory of a port you want to tweak.

If you have suggestions to make this easier, fill free to elaborate :wink:
